//react
import { useRef } from "react";

// libs
import { Pencil, Trash2 } from "lucide-react";

// ui
import { Button } from "@/components/ui/button";

// components
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

// types
import type { TransactionApi } from "../types";

// utils
import {
    formatDate,
    formatCurrency,
    formatBoolean,
    formatTransactionType,
    formatRecurrence,
} from "@/lib/utils/formatters";

type TransactionTableProps = {
    transactions: TransactionApi[];
    onEdit?: (transaction: TransactionApi) => void;
    onDelete?: (transaction: TransactionApi) => void;
};

const TransactionTable = ({ transactions, onEdit, onDelete }: TransactionTableProps) => {
    const scrollAreaRef = useRef<HTMLDivElement | null>(null);

    const renderTableBody = () => {
        return transactions.map((transaction) => {
            return (
                <TableRow key={transaction.id}>
                    <TableCell>{formatCurrency(transaction.amount)}</TableCell>
                    <TableCell>{formatDate(transaction.transactionDate)}</TableCell>
                    <TableCell>{formatTransactionType(transaction.type)}</TableCell>
                    <TableCell>{formatRecurrence(transaction.recurrence)}</TableCell>
                    <TableCell>{transaction.description}</TableCell>
                    <TableCell>{formatBoolean(transaction.isAutoGenerated)}</TableCell>
                    <TableCell>{transaction.originTransactionId ?? "-"}</TableCell>
                    <TableCell>{formatDate(transaction.createdAt)}</TableCell>
                    <TableCell>{formatDate(transaction.updatedAt)}</TableCell>
                    <TableCell>
                        <div className="flex items-center gap-1">
                            <Button
                                size="icon-sm"
                                variant="ghost"
                                onClick={() => onEdit?.(transaction)}
                                aria-label={`Editar ${transaction.description}`}
                                disabled={!onEdit}
                            >
                                <Pencil className="size-4" />
                            </Button>

                            <Button
                                size="icon-sm"
                                variant="ghost"
                                onClick={() => onDelete?.(transaction)}
                                aria-label={`Excluir ${transaction.description}`}
                                disabled={!onDelete}
                            >
                                <Trash2 className="size-4 text-destructive" />
                            </Button>
                        </div>
                    </TableCell>
                </TableRow>
            );
        });
    };

    return (
        <div className="rounded-xl border">
            <div ref={scrollAreaRef} className="max-h-[60vh] overflow-y-auto">
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead>Valor</TableHead>
                            <TableHead>Data</TableHead>
                            <TableHead>Tipo</TableHead>
                            <TableHead>Recorrência</TableHead>
                            <TableHead>Descrição</TableHead>
                            <TableHead>Automática</TableHead>
                            <TableHead>Transação origem</TableHead>
                            <TableHead>Criado em</TableHead>
                            <TableHead>Atualizado em</TableHead>
                            <TableHead className="w-28">Ações</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>{renderTableBody()}</TableBody>
                </Table>
            </div>
        </div>
    );
};

export default TransactionTable;