export type FinancialTransactionType = 1 | 2 | 3;

export type RecurrenceType = 0 | 1;

export type TransactionApi = {
  id: string;
  userId: string;
  transactionCategoryId: string | null;
  amount: number;
  transactionDate: string;
  type: FinancialTransactionType;
  recurrence: RecurrenceType;
  description: string;
  isAutoGenerated: boolean;
  originTransactionId: string | null;
  createdAt: string;
  updatedAt: string;
};

import type { CategoryApi } from "@/app/[locale]/(app)/categories/types";

export type TransactionWithCategory = TransactionApi & {
  category?: CategoryApi;
};
