using SmartBudgetPro.Application.Common.DTOs;
using SmartBudgetPro.Application.Interfaces;

namespace SmartBudgetPro.Application.UseCases.Transaction.GetAllTransaction
{
    public class GetAllTransaction (ITransactionRepository transactionRepository)
    {
        public async Task<IEnumerable<TransactionDTO>> ExecuteAsync()
        {
            var transactions = await transactionRepository.GetAllAsync();

            return transactions.Select(t => new TransactionDTO(
                t.Id,
                t.UserId,
                t.TransactionCategoryId,
                t.Amount,
                t.TransactionDate,
                t.Type,
                t.Recurrence,
                t.Description,
                t.IsAutoGenerated,
                t.OriginTransactionId,
                t.CreatedAt,
                t.UpdatedAt
            ));
        }
    }
}
