services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
      Redis__ConnectionString: ${Redis__ConnectionString}
      Jwt__Key: ${Jwt__Key}
      Email__ApiKey: ${Email__ApiKey}
      Email__FromEmail: ${Email__FromEmail}
      FrontendUrl: ${FrontendUrl}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_APP_URL: http://localhost:3000

    ports:
      - "3000:3000"
    environment:
      API_URL: http://backend:8080/api/v1/
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
