using SmartBudgetPro.Domain.Transactions;

namespace SmartBudgetPro.Application.Common.DTOs;

public record TransactionDTO(
    Guid Id,
    Guid UserId,
    Guid? TransactionCategoryId,
    decimal Amount,
    DateTime TransactionDate,
    TransactionType Type,
    RecurrenceType Recurrence,
    string Description,
    bool IsAutoGenerated,
    Guid? OriginTransactionId,
    DateTime CreatedAt,
    DateTime UpdatedAt
);
