namespace SmartBudgetPro.Domain;

public class Transaction
{
    private const int MaxDescriptionLength = 200;

    public Guid Id { get; private set; }
    public Guid? TransactionCategoryId { get; private set; }
    public Guid UserId { get; private set; }
    public decimal Amount { get; private set; }
    public DateTime TransactionDate { get; private set; }
    public TransactionType Type { get; private set; }
    public RecurrenceType Recurrence { get; private set; }
    public Guid? OriginTransactionId { get; private set; }
    public bool IsAutoGenerated { get; private set; }
    public string Description { get; private set; } = string.Empty;
    public DateTime CreatedAt { get; private set; }
    public DateTime UpdatedAt { get; private set; }

    private Transaction() { } // For EF Core

    private Transaction(
        Guid userId,
        Guid? categoryId,
        decimal amount,
        DateTime transactionDate,
        TransactionType type,
        string description,
        RecurrenceType recurrence,
        Guid? originTransactionId,
        bool isAutoGenerated)
    {
        if (userId == Guid.Empty)
            throw new ArgumentException("Invalid userId.", nameof(userId));

        if (amount <= 0)
            throw new ArgumentException("Amount must be greater than zero.", nameof(amount));

        if (string.IsNullOrWhiteSpace(description))
            throw new ArgumentException("Description is required.", nameof(description));

        if (!Enum.IsDefined(type))
            throw new ArgumentOutOfRangeException(nameof(type), "Transaction type is invalid.");

        if (!Enum.IsDefined(recurrence))
            throw new ArgumentOutOfRangeException(nameof(recurrence), "Recurrence type is invalid.");

        var normalizedDescription = description.Trim();

        if (normalizedDescription.Length > MaxDescriptionLength)
            throw new ArgumentException($"Description must have at most {MaxDescriptionLength} characters.", nameof(description));

        if (type == TransactionType.Expense && categoryId is null)
            throw new ArgumentException("Category is required for expense transactions.", nameof(categoryId));

        if (type == TransactionType.Transfer && categoryId is not null)
            throw new ArgumentException("Transfer transactions must not have category.", nameof(categoryId));

        Id = Guid.NewGuid();
        UserId = userId;
        TransactionCategoryId = categoryId;
        Amount = amount;
        TransactionDate = transactionDate;
        Type = type;
        Recurrence = recurrence;
        OriginTransactionId = originTransactionId;
        IsAutoGenerated = isAutoGenerated;
        Description = normalizedDescription;
        CreatedAt = DateTime.UtcNow;
        UpdatedAt = DateTime.UtcNow;
    }

    public static Transaction Create(
        Guid userId,
        Guid? categoryId,
        decimal amount,
        DateTime transactionDate,
        TransactionType type,
        string description,
        RecurrenceType recurrence = RecurrenceType.None)
    {
        return new Transaction(
            userId,
            categoryId,
            amount,
            transactionDate,
            type,
            description,
            recurrence,
            originTransactionId: null,
            isAutoGenerated: false);
    }

    public Transaction GenerateNextMonthlyOccurrence(DateTime nextTransactionDate)
    {
        if (Recurrence != RecurrenceType.Monthly)
            throw new InvalidOperationException("Only monthly recurring transactions can generate next occurrence.");

        if (nextTransactionDate <= TransactionDate)
            throw new ArgumentException("Next transaction date must be later than the current transaction date.", nameof(nextTransactionDate));

        return new Transaction(
            UserId,
            TransactionCategoryId,
            Amount,
            nextTransactionDate,
            Type,
            Description,
            Recurrence,
            originTransactionId: Id,
            isAutoGenerated: true);
    }

    public void Update(
        Guid? categoryId,
        decimal amount,
        DateTime transactionDate,
        TransactionType type,
        string description,
        RecurrenceType recurrence)
    {
        if (amount <= 0)
            throw new ArgumentException("Amount must be greater than zero.", nameof(amount));

        if (string.IsNullOrWhiteSpace(description))
            throw new ArgumentException("Description is required.", nameof(description));

        if (!Enum.IsDefined(type))
            throw new ArgumentOutOfRangeException(nameof(type), "Transaction type is invalid.");

        if (!Enum.IsDefined(recurrence))
            throw new ArgumentOutOfRangeException(nameof(recurrence), "Recurrence type is invalid.");

        var normalizedDescription = description.Trim();

        if (normalizedDescription.Length > MaxDescriptionLength)
            throw new ArgumentException($"Description must have at most {MaxDescriptionLength} characters.", nameof(description));

        if (type == TransactionType.Expense && categoryId is null)
            throw new ArgumentException("Category is required for expense transactions.", nameof(categoryId));

        if (type == TransactionType.Transfer && categoryId is not null)
            throw new ArgumentException("Transfer transactions must not have category.", nameof(categoryId));

        TransactionCategoryId = categoryId;
        Amount = amount;
        TransactionDate = transactionDate;
        Type = type;
        Description = normalizedDescription;
        Recurrence = recurrence;
        UpdatedAt = DateTime.UtcNow;
    }
}
