using FluentValidation;
using SmartBudgetPro.Application.Common.DTOs;
using SmartBudgetPro.Application.Interfaces;
using SmartBudgetPro.Shared.Pagination;

namespace SmartBudgetPro.Application.UseCases.Transaction.GetAllTransaction
{
    public class GetAllFinancialTransactionUseCase (
        IFinancialTransactionRepository transactionRepository,
        IValidator<GetAllFinancialTransactionUseCaseInput> validator)
    {
        public async Task<PagedResult<FinancialTransactionDTO>> ExecuteAsync(GetAllFinancialTransactionUseCaseInput input)
        {
            await validator.ValidateAndThrowAsync(input);

            var skip = (input.Page - 1) * input.PageSize;
            var transactions = await transactionRepository.GetByUserIdPagedAsync(input.UserId, skip, input.PageSize);
            var totalCount = await transactionRepository.CountByUserIdAsync(input.UserId);

            var items = transactions.Select(t => new FinancialTransactionDTO(
                t.Id,
                t.UserId,
                t.TransactionCategoryId,
                t.Amount,
                t.TransactionDate,
                t.Type,
                t.Recurrence,
                t.Description,
                t.IsAutoGenerated,
                t.OriginTransactionId,
                t.CreatedAt,
                t.UpdatedAt
            ));

            return new PagedResult<FinancialTransactionDTO>(items, totalCount, input.Page, input.PageSize);
        }
    }
}
