using SmartBudgetPro.Application.Common.DTOs;
using SmartBudgetPro.Application.Interfaces;

namespace SmartBudgetPro.Application.UseCases.Transaction.GetAllTransaction
{
    public class GetAllFinancialTransactionUseCase (IFinancialTransactionRepository transactionRepository)
    {
        public async Task<IEnumerable<FinancialTransactionDTO>> ExecuteAsync(Guid userId)
        {
            var transactions = await transactionRepository.GetByUserIdAsync(userId);

            return transactions.Select(t => new FinancialTransactionDTO(
                t.Id,
                t.UserId,
                t.TransactionCategoryId,
                t.Amount,
                t.TransactionDate,
                t.Type,
                t.Recurrence,
                t.Description,
                t.IsAutoGenerated,
                t.OriginTransactionId,
                t.CreatedAt,
                t.UpdatedAt
            ));
        }
    }
}
