using FluentAssertions;
using SmartBudgetPro.Domain.Transactions;
using SmartBudgetPro.Shared.Exceptions;

namespace SmartBudgetPro.Tests.Domain;

public class FinancialTransactionTests
{
    private static readonly Guid ValidUserId = Guid.NewGuid();
    private static readonly Guid ValidCategoryId = Guid.NewGuid();
    private static readonly DateTime ValidDate = new(2026, 6, 1);

    // ── Create ────────────────────────────────────────────────────────────────

    [Fact]
    public void Create_ValidData_ShouldCreateTransactionCorrectly()
    {
        // Arrange / Act
        var transaction = FinancialTransaction.Create(
            ValidUserId,
            ValidCategoryId,
            amount: 250m,
            transactionDate: ValidDate,
            type: FinancialTransactionType.Expense,
            description: "Supermercado");

        // Assert
        transaction.UserId.Should().Be(ValidUserId);
        transaction.TransactionCategoryId.Should().Be(ValidCategoryId);
        transaction.Amount.Should().Be(250m);
        transaction.TransactionDate.Should().Be(ValidDate);
        transaction.Type.Should().Be(FinancialTransactionType.Expense);
        transaction.Description.Should().Be("Supermercado");
        transaction.IsAutoGenerated.Should().BeFalse();
        transaction.OriginTransactionId.Should().BeNull();
        transaction.Id.Should().NotBe(Guid.Empty);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(-1)]
    [InlineData(-999.99)]
    public void Create_AmountLessThanOrEqualToZero_ShouldThrowException(decimal amount)
    {
        // Arrange / Act
        var act = () => FinancialTransaction.Create(
            ValidUserId,
            ValidCategoryId,
            amount,
            ValidDate,
            FinancialTransactionType.Expense,
            "Descrição");

        // Assert
        act.Should().Throw<BusinessBadRequestException>()
            .WithMessage("*Amount*");
    }

    [Fact]
    public void Create_ExpenseWithoutCategory_ShouldThrowException()
    {
        // Arrange / Act
        var act = () => FinancialTransaction.Create(
            ValidUserId,
            categoryId: null,
            amount: 100m,
            transactionDate: ValidDate,
            type: FinancialTransactionType.Expense,
            description: "Sem categoria");

        // Assert
        act.Should().Throw<BusinessBadRequestException>()
            .WithMessage("*Category*");
    }

    [Fact]
    public void Create_TransferWithCategory_ShouldThrowException()
    {
        // Arrange / Act
        var act = () => FinancialTransaction.Create(
            ValidUserId,
            categoryId: ValidCategoryId,
            amount: 100m,
            transactionDate: ValidDate,
            type: FinancialTransactionType.Transfer,
            description: "Transferência com categoria");

        // Assert
        act.Should().Throw<BusinessBadRequestException>()
            .WithMessage("*Transfer*");
    }

    // ── GenerateNextMonthlyOccurrence ─────────────────────────────────────────

    [Fact]
    public void GenerateNextMonthlyOccurrence_DateEarlierThanCurrent_ShouldThrowException()
    {
        // Arrange
        var transaction = FinancialTransaction.Create(
            ValidUserId,
            ValidCategoryId,
            amount: 100m,
            transactionDate: new DateTime(2026, 6, 1),
            type: FinancialTransactionType.Expense,
            description: "Recorrente",
            recurrence: RecurrenceType.Monthly);

        // Act
        var act = () => transaction.GenerateNextMonthlyOccurrence(new DateTime(2026, 5, 1));

        // Assert
        act.Should().Throw<BusinessBadRequestException>()
            .WithMessage("*later*");
    }

    [Fact]
    public void GenerateNextMonthlyOccurrence_ValidDate_ShouldGenerateWithIsAutoGeneratedTrue()
    {
        // Arrange
        var origin = FinancialTransaction.Create(
            ValidUserId,
            ValidCategoryId,
            amount: 150m,
            transactionDate: new DateTime(2026, 6, 1),
            type: FinancialTransactionType.Expense,
            description: "Aluguel",
            recurrence: RecurrenceType.Monthly);

        var nextDate = new DateTime(2026, 7, 1);

        // Act
        var next = origin.GenerateNextMonthlyOccurrence(nextDate);

        // Assert
        next.IsAutoGenerated.Should().BeTrue();
        next.OriginTransactionId.Should().Be(origin.Id);
        next.TransactionDate.Should().Be(nextDate);
        next.Amount.Should().Be(origin.Amount);
        next.Description.Should().Be(origin.Description);
        next.UserId.Should().Be(origin.UserId);
        next.TransactionCategoryId.Should().Be(origin.TransactionCategoryId);
        next.Recurrence.Should().Be(RecurrenceType.Monthly);
    }

    [Fact]
    public void GenerateNextMonthlyOccurrence_NonMonthlyRecurrence_ShouldThrowException()
    {
        // Arrange
        var transaction = FinancialTransaction.Create(
            ValidUserId,
            ValidCategoryId,
            amount: 100m,
            transactionDate: ValidDate,
            type: FinancialTransactionType.Expense,
            description: "Não recorrente",
            recurrence: RecurrenceType.None);

        // Act
        var act = () => transaction.GenerateNextMonthlyOccurrence(ValidDate.AddMonths(1));

        // Assert
        act.Should().Throw<BusinessConflictException>()
            .WithMessage("*monthly*");
    }
}
