using SmartBudgetPro.Shared.Exceptions;

namespace SmartBudgetPro.Domain.Transactions;

public class FinancialTransaction
{
    private const int MaxDescriptionLength = 200;

    public Guid Id { get; private set; }
    public Guid? TransactionCategoryId { get; private set; }
    public Guid UserId { get; private set; }
    public decimal Amount { get; private set; }
    public DateTime TransactionDate { get; private set; }
    public FinancialTransactionType Type { get; private set; }
    public RecurrenceType Recurrence { get; private set; }
    public Guid? OriginTransactionId { get; private set; }
    public bool IsAutoGenerated { get; private set; }
    public string Description { get; private set; } = string.Empty;
    public DateTime CreatedAt { get; private set; }
    public DateTime UpdatedAt { get; private set; }

    private FinancialTransaction() { } // For EF Core

    private FinancialTransaction(
        Guid userId,
        Guid? categoryId,
        decimal amount,
        DateTime transactionDate,
        FinancialTransactionType type,
        string description,
        RecurrenceType recurrence,
        Guid? originTransactionId,
        bool isAutoGenerated)
    {
        if (userId == Guid.Empty)
            throw new BusinessBadRequestException("Invalid userId.");

        if (amount <= 0)
            throw new BusinessBadRequestException("Amount must be greater than zero.");

        if (string.IsNullOrWhiteSpace(description))
            throw new BusinessBadRequestException("Description is required.");

        if (!Enum.IsDefined(type))
            throw new ArgumentOutOfRangeException(nameof(type), "Transaction type is invalid.");

        if (!Enum.IsDefined(recurrence))
            throw new ArgumentOutOfRangeException(nameof(recurrence), "Recurrence type is invalid.");

        var normalizedDescription = description.Trim();

        if (normalizedDescription.Length > MaxDescriptionLength)
            throw new BusinessBadRequestException($"Description must have at most {MaxDescriptionLength} characters.");

        if (type == FinancialTransactionType.Expense && categoryId is null)
            throw new BusinessBadRequestException("Category is required for expense transactions.");

        if (type == FinancialTransactionType.Transfer && categoryId is not null)
            throw new BusinessBadRequestException("Transfer transactions must not have category.");

        Id = Guid.NewGuid();
        UserId = userId;
        TransactionCategoryId = categoryId;
        Amount = amount;
        TransactionDate = transactionDate;
        Type = type;
        Recurrence = recurrence;
        OriginTransactionId = originTransactionId;
        IsAutoGenerated = isAutoGenerated;
        Description = normalizedDescription;
        CreatedAt = DateTime.UtcNow;
        UpdatedAt = DateTime.UtcNow;
    }

    public static FinancialTransaction Create(
        Guid userId,
        Guid? categoryId,
        decimal amount,
        DateTime transactionDate,
        FinancialTransactionType type,
        string description,
        RecurrenceType recurrence = RecurrenceType.None)
    {
        return new FinancialTransaction(
            userId,
            categoryId,
            amount,
            transactionDate,
            type,
            description,
            recurrence,
            originTransactionId: null,
            isAutoGenerated: false);
    }

    public FinancialTransaction GenerateNextMonthlyOccurrence(DateTime nextTransactionDate)
    {
        if (Recurrence != RecurrenceType.Monthly)
            throw new BusinessConflictException("Only monthly recurring transactions can generate next occurrence.");

        if (nextTransactionDate <= TransactionDate)
            throw new BusinessBadRequestException("Next transaction date must be later than the current transaction date.");

        return new FinancialTransaction(
            UserId,
            TransactionCategoryId,
            Amount,
            nextTransactionDate,
            Type,
            Description,
            Recurrence,
            originTransactionId: Id,
            isAutoGenerated: true);
    }

    public void Update(
        Guid? categoryId,
        decimal amount,
        DateTime transactionDate,
        FinancialTransactionType type,
        string description,
        RecurrenceType recurrence)
    {
        if (amount <= 0)
            throw new BusinessBadRequestException("Amount must be greater than zero.");

        if (string.IsNullOrWhiteSpace(description))
            throw new BusinessBadRequestException("Description is required.");

        if (!Enum.IsDefined(type))
            throw new ArgumentOutOfRangeException(nameof(type), "Transaction type is invalid.");

        if (!Enum.IsDefined(recurrence))
            throw new ArgumentOutOfRangeException(nameof(recurrence), "Recurrence type is invalid.");

        var normalizedDescription = description.Trim();

        if (normalizedDescription.Length > MaxDescriptionLength)
            throw new BusinessBadRequestException($"Description must have at most {MaxDescriptionLength} characters.");

        if (type == FinancialTransactionType.Expense && categoryId is null)
            throw new BusinessBadRequestException("Category is required for expense transactions.");

        if (type == FinancialTransactionType.Transfer && categoryId is not null)
            throw new BusinessBadRequestException("Transfer transactions must not have category.");

        TransactionCategoryId = categoryId;
        Amount = amount;
        TransactionDate = transactionDate;
        Type = type;
        Description = normalizedDescription;
        Recurrence = recurrence;
        UpdatedAt = DateTime.UtcNow;
    }
}
