"use client";

//react
import { useRef } from "react";

// i18n
import { useTranslations } from "next-intl";

// libs
import { Pencil, ReceiptText, Trash2 } from "lucide-react";

// ui
import { Button } from "@/components/ui/button";

// components
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

import { ThemeIcon } from "@/app/[locale]/(app)/categories/components/theme-icons";

import { ICONT_THEME } from "@/app/[locale]/(app)/categories/constants/icons-theme";

import { RecurrenceBadge, TransactionTypeBadge } from "./transaction-badges";

// types
import type { TransactionApi, TransactionWithCategory } from "../types";

// utils
import {
    formatDate,
    formatCurrency,
} from "@/lib/utils/formatters";

type TransactionTableProps = {
    transactions: TransactionWithCategory[];
    onEdit?: (transaction: TransactionWithCategory) => void;
    onDelete?: (transaction: TransactionWithCategory) => void;
};

const TransactionTable = ({ transactions, onEdit, onDelete }: TransactionTableProps) => {
    const t = useTranslations("transactions");
    const scrollAreaRef = useRef<HTMLDivElement | null>(null);

    const mapTransactionType = (type: TransactionApi["type"]): "receita" | "despesa" | "transferencia" => {
        
        if (type === 1) return "receita";

        if (type === 2) return "despesa";

        return "transferencia";
    };

    const renderCategory = (transaction: TransactionWithCategory) => {
        if (!transaction.category) {
            return <span className="text-muted-foreground">-</span>;
        }

        const theme = ICONT_THEME.find((item) => item.iconKey === transaction.category?.icon);

        return (
            <div className="flex items-center gap-2">
                <div
                    className={`flex size-7 items-center justify-center rounded-md text-white ${theme?.colorClass ?? "bg-muted"}`}
                >
                    <ThemeIcon iconKey={transaction.category.icon} className="size-4" />
                </div>
                <span className="truncate">{transaction.category.name}</span>
            </div>
        );
    };

    const renderTableBody = () => {
        if (transactions.length === 0) {
            return (
                <TableRow>
                    <TableCell colSpan={7} className="h-52 text-center">
                        <div className="flex flex-col items-center gap-3 text-muted-foreground">
                            <ReceiptText className="size-10 opacity-30" />
                            <span className="text-sm">{t("table.empty")}</span>
                        </div>
                    </TableCell>
                </TableRow>
            );
        }

        return transactions.map((transaction) => (
            <TableRow key={transaction.id}>
                <TableCell className="min-w-25">{formatCurrency(transaction.amount)}</TableCell>
                <TableCell className="min-w-30">{formatDate(transaction.transactionDate)}</TableCell>
                <TableCell className="min-w-25">
                    <TransactionTypeBadge type={mapTransactionType(transaction.type)} />
                </TableCell>
                <TableCell className="min-w-32.5">
                    <RecurrenceBadge recurrence={transaction.recurrence} isAutoGenerated={transaction.isAutoGenerated} />
                </TableCell>
                <TableCell className="min-w-50">{transaction.description}</TableCell>
                <TableCell className="min-w-37.5">{renderCategory(transaction)}</TableCell>
                <TableCell className="min-w-20">
                    <div className="flex items-center gap-1">
                        <Button
                            size="icon-sm"
                            variant="ghost"
                            onClick={() => onEdit?.(transaction)}
                            aria-label={t("actions.editAriaLabel", { description: transaction.description })}
                            disabled={!onEdit}
                        >
                            <Pencil className="size-4" />
                        </Button>

                        <Button
                            size="icon-sm"
                            variant="ghost"
                            onClick={() => onDelete?.(transaction)}
                            aria-label={t("actions.deleteAriaLabel", { description: transaction.description })}
                            disabled={!onDelete}
                        >
                            <Trash2 className="size-4 text-destructive" />
                        </Button>
                    </div>
                </TableCell>
            </TableRow>
        ));
    };

    return (
        <div className="rounded-xl border">
            <div ref={scrollAreaRef} className="max-h-[60vh] overflow-y-auto">
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead className="min-w-25">{t("table.amount")}</TableHead>
                            <TableHead className="min-w-30">{t("table.date")}</TableHead>
                            <TableHead className="min-w-25">{t("table.type")}</TableHead>
                            <TableHead className="min-w-32.5">{t("table.recurrence")}</TableHead>
                            <TableHead className="min-w-50">{t("table.description")}</TableHead>
                            <TableHead className="min-w-37.5">{t("table.category")}</TableHead>
                            <TableHead className="min-w-20">{t("table.actions")}</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>{renderTableBody()}</TableBody>
                </Table>
            </div>
        </div>
    );
};

export default TransactionTable;
