"use client";

// i18n
import { useTranslations } from "next-intl";

//components
import { Badge } from "@/components/ui/badge";

type TransactionType = "receita" | "despesa" | "transferencia";

type RecurrenceVariant = "unica" | "recorrente" | "recorrenteAuto";

type TransactionTypeBadgeProps = {
  type: TransactionType;
};

type RecurrenceBadgeProps = {
  recurrence: 0 | 1;
  isAutoGenerated: boolean;
};

const transactionTypeClassName: Record<TransactionType, string> = {
  receita: "bg-emerald-100 text-emerald-800 hover:bg-emerald-100",
  despesa: "bg-rose-100 text-rose-800 hover:bg-rose-100",
  transferencia: "bg-sky-100 text-sky-800 hover:bg-sky-100",
};

const recurrenceClassName: Record<RecurrenceVariant, string> = {
  unica: "bg-zinc-100 text-zinc-800 hover:bg-zinc-100",
  recorrente: "bg-amber-100 text-amber-800 hover:bg-amber-100",
  recorrenteAuto: "bg-violet-100 text-violet-800 hover:bg-violet-100",
};

export function TransactionTypeBadge({ type }: Readonly<TransactionTypeBadgeProps>) {
  const t = useTranslations("transactions.types");

  return (
    <Badge className={transactionTypeClassName[type]}>
      {t(type)}
    </Badge>
  );
}

export function RecurrenceBadge({ recurrence, isAutoGenerated }: Readonly<RecurrenceBadgeProps>) {
  const t = useTranslations("transactions.recurrence");

  const variant: RecurrenceVariant =
    recurrence === 0 ? "unica" : isAutoGenerated ? "recorrenteAuto" : "recorrente";

  return (
    <Badge className={recurrenceClassName[variant]}>
      {t(variant)}
    </Badge>
  );
}
