using Microsoft.EntityFrameworkCore;
using SmartBudgetPro.Application.Interfaces;
using SmartBudgetPro.Domain.Transactions;

namespace SmartBudgetPro.Infrastructure.Persistence.Repositories
{
    public class FinancialTransactionRepository(AppDbContext context) : IFinancialTransactionRepository
    {
        public async Task AddAsync(FinancialTransaction transaction)
        {
            await context.FinancialTransactions.AddAsync(transaction);

            await context.SaveChangesAsync();
        }

        public async Task<IEnumerable<FinancialTransaction>> GetAllAsync()
        {
            return await context.FinancialTransactions.ToListAsync();
        }

        public async Task<IEnumerable<FinancialTransaction>> GetAllMonthlyRecurringAsync()
        {
            return await context.FinancialTransactions
                .Where(t => t.Recurrence == RecurrenceType.Monthly && !t.IsAutoGenerated)
                .ToListAsync();
        }

        public async Task<IEnumerable<FinancialTransaction>> GetByUserIdAsync(Guid userId)
        {
            return await context.FinancialTransactions
                .Where(t => t.UserId == userId)
                .ToListAsync();
        }

        public async Task<IEnumerable<FinancialTransaction>> GetByUserIdPagedAsync(
            Guid userId, int skip, int take,
            string? description = null,
            Guid? categoryId = null,
            DateTime? date = null,
            FinancialTransactionType? type = null,
            RecurrenceType? recurrence = null)
        {
            var query = BuildFilteredQuery(userId, description, categoryId, date, type, recurrence);

            return await query
                .OrderByDescending(t => t.TransactionDate)
                .ThenByDescending(t => t.CreatedAt)
                .ThenByDescending(t => t.Id)
                .Skip(skip)
                .Take(take)
                .ToListAsync();
        }

        public async Task<int> CountByUserIdAsync(
            Guid userId,
            string? description = null,
            Guid? categoryId = null,
            DateTime? date = null,
            FinancialTransactionType? type = null,
            RecurrenceType? recurrence = null)
        {
            var query = BuildFilteredQuery(userId, description, categoryId, date, type, recurrence);

            return await query.CountAsync();
        }

        private IQueryable<FinancialTransaction> BuildFilteredQuery(
            Guid userId,
            string? description,
            Guid? categoryId,
            DateTime? date,
            FinancialTransactionType? type,
            RecurrenceType? recurrence)
        {
            var query = context.FinancialTransactions.Where(t => t.UserId == userId);

            var normalizedDescription = description?.Trim();
            if (!string.IsNullOrWhiteSpace(normalizedDescription))
                query = query.Where(t => t.Description.ToLower().Contains(normalizedDescription.ToLower()));

            if (categoryId.HasValue)
                query = query.Where(t => t.TransactionCategoryId == categoryId.Value);

            if (date.HasValue)
            {
                var startOfDay = DateTime.SpecifyKind(date.Value.Date, DateTimeKind.Utc);
                var endOfDay = startOfDay.AddDays(1);
                query = query.Where(t => t.TransactionDate >= startOfDay && t.TransactionDate < endOfDay);
            }

            if (type.HasValue)
                query = query.Where(t => t.Type == type.Value);

            if (recurrence.HasValue)
                query = query.Where(t => t.Recurrence == recurrence.Value);

            return query;
        }

        public async Task<FinancialTransaction?> GetByIdAsync(Guid transactionId)
        {
            return await context.FinancialTransactions.FindAsync(transactionId);
        }

        public async Task<bool> ExistsOccurrenceForMonthAsync(Guid originTransactionId, int year, int month)
        {
            return await context.FinancialTransactions
                .AnyAsync(t => t.OriginTransactionId == originTransactionId
                    && t.TransactionDate.Year == year
                    && t.TransactionDate.Month == month);
        }

        public async Task UpdateAsync(FinancialTransaction transaction)
        {
            context.FinancialTransactions.Update(transaction);
            await context.SaveChangesAsync();
        }

        public async Task DeleteAsync(Guid transactionId)
        {
            await context.FinancialTransactions
                .Where(transaction => transaction.Id == transactionId)
                .ExecuteDeleteAsync();
        }

        public async Task<bool> ExistsTransactionByCategoryAsync(Guid categoryId)
        {
            return await context.FinancialTransactions
                .AnyAsync(transaction => transaction.TransactionCategoryId == categoryId);
        }

        public async Task<decimal> GetTotalExpensesByCategoryAndPeriodAsync(Guid categoryId, int year, int month)
        {
            return await context.FinancialTransactions
                .Where(t => t.TransactionCategoryId == categoryId
                    && t.Type == FinancialTransactionType.Expense
                    && t.TransactionDate.Year == year
                    && t.TransactionDate.Month == month)
                .SumAsync(t => t.Amount);
        }
    }
}
